// -------------------------------------------------------------     
// * this is game text file header, generated by gd *     
      
// multi-language array count is 5, the id : en - 0, es - 1, pt - 2, fr - 3, it - 4      
      
// you can change the count      
// -------------------------------------------------------------     
      
#pragma once     
#define LANGUAGE_COUNT 5     
      
const char TEXT_LEVEL[][530] = { "level%d",
    "等级%d" 
   };  
const char the_loginmain_account[][544] = { "Account Number",
    "请输入账号" 
   };  
const char the_loginmain_password[][532] = { "Password",
    "请输入密码" 
   };  
const char the_loginmain_register[][548] = { "Register Account",
    "账号注册" 
   };  
const char the_loginmain_option[][528] = { "Option",
    "游戏设置" 
   };  
const char the_loginmain_designer[][532] = { "Designer",
    "制作人员" 
   };  
const char the_loginmain_designer_text[][724] = { "Game Design:horde,Ryudo\nArt Designer:Wang qi\nLead Engineers:Huyan Jiaquan\ntechnical support:Wei zheng",
    "策划:张兴智,侯杰\n美术:王琦\n程序:呼延甲泉\n技术测试:曹岩\n音乐制作:尹航" 
   };  
const char the_message_cheat[][570] = { "you are cheating!",
    "你的存档被人为修改，因此您有作弊嫌疑，请接受系统处罚!" 
   };  
const char the_message_cheat_json[][566] = { "%s file has been changed!",
    "文件%s被修改，请您还原，否则以作弊论处!" 
   };  
const char the_message_alert[][526] = { "alert",
    "警告" 
   };  
const char baseitem_json[][580] = { "311f61b07608bf8c893f2f12c50cff60",
    "0" 
   };  
const char basepet_json[][580] = { "5b048c7458ffc358fb17ea36a52488b8",
    "0" 
   };  
const char eventlimit_json[][580] = { "715a1a3f52027d5715eb3e5b445570c3",
    "0" 
   };  
const char eventpoint_json[][580] = { "a84f0d22a556ca2c4df95febfcb68d9b",
    "0" 
   };  
const char eventrun_json[][580] = { "017c1187ed0d18deaf49e11110c546df",
    "0" 
   };  
const char petanimation_json[][580] = { "52d2378e4d86c5a76bfe25d6b075aaf1",
    "0" 
   };  
const char petexp_json[][580] = { "38b97d83c614355b96af2c2531a7ce46",
    "0" 
   };  
const char skillList_json[][580] = { "a11dff0a5a1af487f61b5aaf6c5884f0",
    "0" 
   };  
const char subevent_json[][580] = { "024c7a58ef9680f114322709107873d4",
    "0" 
   };  
const char minigame3_score_json[][580] = { "27390fcf127471326a6601db79083edc",
    "0" 
   };  
const char gametip_1[][560] = { "54545",
    "小提示：喂食电池类食材可让宠物进化成熊猫形态" 
   };  
const char gametip_2[][556] = { "54545",
    "小提示：喂食肉类食材可让宠物进化成龙形态" 
   };  
const char gametip_3[][554] = { "54545",
    "小提示：让宠物玩小游戏可以获得各种奖励" 
   };  
const char gametip_4[][568] = { "54545",
    "小提示：战斗前看清对手的信息，选择你有较大把握战胜的" 
   };  
const char gametip_5[][560] = { "54545",
    "小提示：每天上线最好把宠物精力值消耗完再休息" 
   };  
const char gametip_6[][552] = { "54545",
    "小提示：战斗总输?给宠物的技能升级!" 
   };  
const char gametip_7[][564] = { "54545",
    "小提示：技能经验池是有上限的，及时升级技能经验!" 
   };  
const char gametip_8[][560] = { "54545",
    "小提示：邀请你的朋友一同享受这款游戏的乐趣!" 
   };  
const char gametip_9[][562] = { "54545",
    "小提示：每个阶段的进化都有机率得到变异的宠物!" 
   };  
const char gametip_10[][562] = { "54545",
    "小提示：第一次进化宠物，需要先将宠物升到5级。" 
   };  
const char gametip_11[][548] = { "54545",
    "小提示：每日都会恢复宠物的精力值" 
   };  
const char message_noevolution[][536] = { "54545",
    "还不能够进行宠物进化" 
   };  
const char message_skillnewlevel[][546] = { "54545",
    "您的宠物技能提升了一个新的等级" 
   };  
const char message_skillmaxlevel[][542] = { "54545",
    "您的宠物技能已经提升至满级" 
   };  
const char message_nofight[][532] = { "54545",
    "您还不能进行战斗" 
   };  
const char message_nominigame[][542] = { "54545",
    "您还不能进行这个迷你小游戏" 
   };  
const char message_tip[][526] = { "54545",
    "提示" 
   };  
const char message_moneypoint_1[][542] = { "54545",
    "花费%d个钻石立即完成喂养" 
   };  
const char message_moneypoint_2[][544] = { "54545",
    "花费%d个钻石立即恢复精力值" 
   };  
const char message_nomoney[][532] = { "54545",
    "您没有足够的金币" 
   };  
const char message_nomoneypoint[][532] = { "54545",
    "您没有足够的钻石" 
   };  
const char message_nostaminapoint[][534] = { "54545",
    "您没有足够的精力值" 
   };  
const char message_moneypoint_3[][536] = { "54545",
    "您需要花费%d个钻石" 
   };  
const char message_peteat_1[][536] = { "54545",
    "需要增加新的喂养栏位" 
   };  
const char message_minigame2[][542] = { "54545",
    "你的宠物击碎了%d个木桩!" 
   };  
const char message_gameshow[][566] = { "54545",
    "(快来挑战我吧!加入魔宠奇缘，快乐hold不住!)" 
   };  
const char fightmessage_win[][550] = { "54545",
    "你的宠物把%s的宠物%s痛打一顿!" 
   };  
const char fightmessage_lost[][556] = { "54545",
    "%s把你的宠物%s痛打一顿!你还能忍吗？" 
   };  
const char fightplayermessage_lost[][552] = { "54545",
    "玩家%s的宠物把你的宠物教育了一番!" 
   };  
const char message_kill[][550] = { "54545",
    "你的宝贝宠物%s完成了一次%d杀!" 
   };  
const char peteat_1[][534] = { "54545",
    "您获得了%d个%s" 
   };  
const char teacher_1[][540] = { "54545",
    "点击可随机更换宠物的资质" 
   };  
const char teacher_2[][540] = { "54545",
    "与你的宠物一起玩小游戏!" 
   };  
const char teacher_3[][550] = { "54545",
    "小游戏可获得各种食材,请点击进入!" 
   };  
const char teacher_4[][552] = { "54545",
    "喂养宠物可以让宠物获得经验用于升级!" 
   };  
const char teacher_5[][530] = { "54545",
    "点击查看成就!" 
   };  
const char teacher_6[][534] = { "54545",
    "点击查看宠物属性!" 
   };  
const char teacher_7[][530] = { "54545",
    "点击进化宠物!" 
   };  
const char teacher_8[][538] = { "54545",
    "与其他玩家的宠物对战!" 
   };  
const char teacher_9[][556] = { "54545",
    "点击技能图标可以让该技能增加经验或升级!" 
   };  
const char shop_1[][528] = { "54545",
    "%d个91豆" 
   };  
      
      
      
      
      
